---
name: Lint Pull Requests
on:
  pull_request:
    branches:
      - main
jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: golang-lint for integration tests
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: integration
          args: --build-tags integration
      - name: golang-lint for long running tests
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: long-run
          args: --build-tags integration
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: terraform format check 
        run: >
          find ./ -name '*.tf' -exec dirname \{\} \; | sort | uniq | 
          parallel terraform fmt -diff -check
